# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:13.1.0
  #amd64: ghcr.io/hassio-addons/base:13.1.0
  armhf: ghcr.io/hassio-addons/base:13.1.0
  armv7: ghcr.io/hassio-addons/base:13.1.0
  #i386: ghcr.io/hassio-addons/base:13.1.0
labels:
  org.opencontainers.image.title: "Additional Devices Addon"
  org.opencontainers.image.description: "Dodatek do obsługi przycisków na zajęcia"
  org.opencontainers.image.source: "https://github.com/AresMaster/HA-addon-classes"
  org.opencontainers.image.licenses: "Apache License 2.0"
