# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Additional Devices Addon
version: "0.0.1a"
slug: monitoring
description: Dodatek do obsługi przycisków na zajęcia (REPOSITORY)
url: "https://github.com/AresMaster/HA-addon-classes"
arch:
  - armhf
  - armv7
  - aarch64
init: false
#map:
#  - share:rw
options:
  mqtt: []
homeassistant_api: true
privileged:
  - SYS_RAWIO
services: 
  - "mqtt:need"
schema:
  server: str?
  ca: str?
  key: str?
  cert: str?
  user: str?
  password: str?
#image: "ghcr.io/home-assistant/{arch}-addon-example"
devices:
  - /dev/gpiomem
  - /dev/mem
gpio: true
